schoolstore_project/credentials/urls.py
from django.urls import path
from . import views

app_name = 'credentials'

urlpatterns = [
        path('register',views.register,name='register'),
        path('login',views.login,name='login'),
        path('logout',views.logout,name='logout'),

]

schoolstore_project/schoolstore_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('storeapp.urls')),
    path("credentials/",include('credentials.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schoolstore_project/storeapp/urls.py
from django.urls import path
from . import views

app_name = 'storeapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('allDept/', views.allDept, name='all_dept'),
    path('allDept/<slug:d_slug>/', views.allDept, name='courses_by_departments'),
    path('user/', views.user, name='user'),
    path('form', views.form, name='form'),
    path('confirm', views.confirm, name='confirm'),
    path('get_courses_by_department/', views.get_courses_by_department, name='get_courses_by_department'),
]

schoolstore_project/credentials/models.py
from django.db import models

# Create your models here.

schoolstore_project/storeapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='department', blank=True)
    wikipedia_url = models.URLField(default='https://en.wikipedia.org/wiki/Default_Page_URL')

    class Meta:
        ordering = ('name',)
        verbose_name = 'department'
        verbose_name_plural = 'departments'

    def get_url(self):
        return reverse('storeapp:courses_by_departments', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Course(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='course', blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        verbose_name = 'course'
        verbose_name_plural = 'courses'


    def __str__(self):
        return '{}'.format(self.name)

schoolstore_project/credentials/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User

def register(request):
    if request.method == 'POST':
        uname = request.POST['user_name']
        password = request.POST['password']
        conpassword = request.POST['conpassword']

        if password == conpassword:
            if User.objects.filter(username=uname).exists():
                messages.error(request, 'Username already taken')
            else:
                user = User.objects.create_user(username=uname, password=password)
                user.save()
                messages.success(request, 'Registration successful. You can now log in.')
                return redirect('/credentials/login')
        else:
            messages.error(request, 'Password mismatched')

    # If there's an error or the request method is not POST, return to the registration page
    return render(request, 'register.html')

def login(request):
        if request.method == 'POST':
                uname = request.POST['user_name']
                password = request.POST['password']

                user = auth.authenticate(username=uname, password=password)

                if user is not None:
                        auth.login(request, user)
                        return redirect('/user')

                else:
                        messages.info(request, 'Invalid Credentials')
                        return redirect('login')
        return render(request, 'login.html')

def logout(request):
                auth.logout(request)
                return redirect('/')

schoolstore_project/storeapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

from storeapp.models import Department, Course


# Create your views here.
def home(request):
    return render(request, 'home.html')


def allDept(request, d_slug=None):
    d_page = None
    product_list = None

    if d_slug is not None:
        d_page = get_object_or_404(Department, slug=d_slug)
        courses = Course.objects.filter(department=d_page)
    else:
        courses = Course.objects.all()

    return render(request, 'home.html', {'department': d_page, 'course': courses})

def user(request):
    return render(request, 'user.html')


def form(request):
    if request.method == 'GET':
        # This is when the form is initially loaded
        departments = Department.objects.all()
        return render(request, 'form.html', {'departments': departments})
    elif request.method == 'POST':
        # Handle form submission if needed
        # You may need to process the form data, save it to the database, etc.
        # After processing, redirect to the appropriate page
        return redirect('storeapp:home')


def get_courses_by_department(request):
    department_id = request.GET.get('department', None)

    if department_id is not None:
        department = get_object_or_404(Department, id=department_id)
        courses = Course.objects.filter(department=department).values('id', 'name')
    else:
        courses = Course.objects.all().values('id', 'name')

    return JsonResponse({'courses': list(courses)})
def confirm(request):
    return render(request, 'confirmation.html')

schoolstore_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/22768845f9.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'navbar.html' %}

    <div class="one">
        {% block content %}
        {% endblock %}
    </div>


    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </div>
</body>
</html>

schoolstore_project/templates/confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Confirmed</title>
    <style>
        /* Common styles */
        body {
            margin: 0;
            padding: 0;
        }

        div {
            text-align: center;
            padding: 20px;
        }

        h1 {
            font-size: 50px;
        }

        img {
            max-width: 40%;
            height: auto;
            margin-top: 20px;
        }

        p {
            margin-top: 20px;
            font-size: 18px;
        }

        /* Link styles */
        a {
            text-decoration: none;
            color: #4CAF50;
            padding: 10px 20px;
            border-radius: 5px;
            background-color: #fff;
            border: 2px solid #4CAF50;
            transition: background-color 0.3s ease, color 0.3s ease;
        }

        a:hover {
            background-color: #4CAF50;
            color: #fff;
        }
    </style>
</head>
<body>

<div>
    <h1>Response Recorded</h1>
    <img src="static/img/confirm.jpg" alt="Order Confirmed Image">
    <p>
        <a href="/">Return to Home Page</a>
    </p>
</div>

</body>
</html>

schoolstore_project/templates/course_options.html
{% for course in courses %}
    <option value="{{ course.id }}">{{ course.name }}</option>
{% endfor %}

schoolstore_project/templates/course_options_partial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for course in courses %}
    <option value="{{ course.id }}">{{ course.name }}</option>
{% endfor %}
</body>
</html>

schoolstore_project/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy;All Copyrights Recieved</p>
</div>

schoolstore_project/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fill the form</title>

    <style>
        form {
            width: 50%;
            margin: auto;
        }

        label {
            display: block;
            margin-bottom: 8px;
        }

        input, select {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
        }

        /* Increase the size of the address field */
        #address {
            height: 100px; /* Adjust the height as needed */
            width: 730px;
        }


        /* Button styling */
        button {
            font-size: 16px; /* Adjust as needed for the desired font size */
            padding: 15px 20px; /* Adjust as needed for the desired padding */
            background-color: #4caf50;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            margin-right: 10px; /* Added margin between buttons */
        }

button:hover {
    background-color: #45a049;
}

        /* Materials Provided */
.materials-checkboxes {
    display: flex;
    flex-wrap: wrap;
}

.material-checkbox {
    margin-right: 15px; /* Adjust as needed for spacing between checkboxes */
    display: flex;
    align-items: center;
}

.material-checkbox input {
    margin-right: 5px; /* Adjust as needed for spacing between checkbox and label */
}

     /* Logout button styling */
        #logout {
            font-size: 16px;
            padding: 15px 20px;
            background-color: #f44336;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        #logout:hover {
            background-color: #d32f2f;
        }


    </style>
</head>
<body>
<h1 style="text-align: center; margin-top: 20px;">Fill The Form</h1>
<form action="{% url 'storeapp:confirm' %}" method="GET">
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required>

    <label for="dob">DOB:</label>
    <input type="date" id="dob" name="dob" required>

    <label for="age">Age:</label>
    <input type="text" id="age" name="age" required>

    <label for="gender">Gender:</label>
    <select id="gender" name="gender" required>
        <option value="male">Male</option>
        <option value="female">Female</option>
        <option value="other">Other</option>
    </select>

    <label for="phone">Phone Number:</label>
    <input type="text" id="phone" name="phone" maxlength="10" pattern="[0-9]{10}" title="Please enter 10 digits" required>

    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required>

    <label for="address">Address:</label>
    <textarea id="address" name="address" rows="4" required></textarea>

     <label for="department">Department:</label>
    <select id="department" name="department">
        {% for dept in departments %}
            <option value="{{ dept.id }}" {% if selected_department and selected_department.id == dept.id %}selected{% endif %}>
                {{ dept.name }}
            </option>
        {% endfor %}
    </select>

    <label for="course">Course:</label>
    <select id="course" name="course">
        {% for course in initial_courses %}
            <option value="{{ course.id }}">{{ course.name }}</option>
        {% endfor %}
    </select>



    <label for="purpose">Purpose:</label>
    <select id="purpose" name="purpose" required>
        <option value="enquiry">Enquiry</option>
        <option value="placeorder">Place Order</option>
        <option value="return">Return</option>
    </select>

    <label>Materials Provided:</label>
<div class="materials-checkboxes">
    <div class="material-checkbox">
        <input type="checkbox" id="notebook" name="materials[]" value="notebook">
        <label for="notebook">Notebook</label>
    </div>

    <div class="material-checkbox">
        <input type="checkbox" id="pen" name="materials[]" value="pen">
        <label for="pen">Pen</label>
    </div>

    <div class="material-checkbox">
        <input type="checkbox" id="examPapers" name="materials[]" value="examPapers">
        <label for="examPapers">Exam Papers</label>
    </div>
</div>

<br>
    <center>
         <button type="submit">Submit</button>
        <a href="{% url 'credentials:logout' %}"><button id="logout" type="button">Logout</button></a>

    </center>


</form>

<script>
document.addEventListener('DOMContentLoaded', function () {
    var departmentDropdown = document.getElementById('department');
    var courseDropdown = document.getElementById('course');

    // Function to fetch and populate courses based on the selected department
    function populateCourses(departmentId) {
        fetch("{% url 'storeapp:get_courses_by_department' %}?department=" + departmentId)
            .then(response => response.json())
            .then(data => {
                // Clear existing options
                courseDropdown.innerHTML = '';
                data.courses.forEach(course => {
                    var option = document.createElement('option');
                    option.value = course.id;
                    option.text = course.name;
                    courseDropdown.add(option);
                });
            })
            .catch(error => console.error('Error fetching courses:', error));
    }

    // Initially populate courses based on the selected department
    populateCourses(departmentDropdown.value);

    // Add change event listener to the department dropdown
    departmentDropdown.addEventListener('change', function () {
        var departmentId = this.value;
        // Populate courses when the department changes
        populateCourses(departmentId);
    });
});
</script>


</body>
</html>

schoolstore_project/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'storeapp:all_dept' %}"> <img src="{% static 'img/logo.png' %}" width="100" height="100"></a>
    </center>
</header>

schoolstore_project/templates/home.html
<head>
    <style>
         button {
            width: 30%;
            padding: 10px;
            background-color: #4caf50;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

         .my_title {
            font-weight: bold;
        }
    </style>
</head>
{% extends 'base.html' %}

{% load static %}

{% block metadescription %}
    {% if department %}
        {{ department.desc | truncatewords:155 }}
    {% else %}
          Find the details
    {% endif %}
{% endblock %}

{% block title %}
    {% if department %}
        {{ department.title }} - School Store
    {% else %}
      Welcome to School Store
    {% endif %}
{% endblock %}


{% block content %}
    <div class="container">
        {% if department %}
            <div class="row my-4">
                <div class="mx-auto">
                    <p><a href="{% url 'storeapp:all_dept' %}">ALL DEPARTMENTS</a></p>
                </div>
            </div>
        {% endif %}

         <h1 class="text-center my_title">GOODWILL SCHOOL</h1>
        <div class="mx-auto">
    {% if department %}
        <img class="my_image" src="{{ department.img.url }}" alt="{{ department.name }}" width="70%">
    {% else %}
        <img class="my_image my_image_padding" src="{% static 'img/banner.jpg' %}" width="100%" height="60%">
    {% endif %}
</div>


        {% if department %}
            <br>
            <div>
                <b><h2 class="text-center">{{ department.name }}</h2></b>
                <center><p class="text-justify">{{ department.desc }}</p></center>
            </div>
        {% else %}
            <div>
                <br>

                <p class="text-justify">
                    Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical
                    Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at
                    Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a
                    Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the
                    undoubtable source.
                </p>
                <center> <a href="credentials/login"><button type="submit" >Login Here</button></a></center>
            </div>
        {% endif %}

    </div>
{% endblock %}

schoolstore_project/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>User Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 500px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
        }

        input[type="text"],
        input[type="email"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: #4caf50;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>User Login</h1>
        <form action="login" method="post">
            {% csrf_token %}
            <input type="text" name="user_name" placeholder="User Name" required>
            <input type="password" name="password" placeholder="Password" required>
            <button type="submit">Login</button>

          {% for msg in messages %}
          {{msg}}
          {% endfor %}
        </form>

        <center><p>Don't have an account? <br><br><a href="register">Register here</a></p></center>
    </div>
</body>
</html>

schoolstore_project/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Include necessary CSS and Bootstrap stylesheets -->
  <!-- Include Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">

  <!-- Include jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <!-- Include Bootstrap JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="credentials/login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="credentials/register">Register</a>
          </li>
          <!-- Add a dropdown menu for categories -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownCategories" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Departments
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownCategories">
              {% for dep in links %}
                <li><a class="dropdown-item" href="{{ dep.wikipedia_url }}">{{ dep.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          <!-- End of dropdown menu -->
        </ul>
      </div>
    </div>
  </nav>

  <!-- No need to include jQuery and Bootstrap JavaScript again -->
</body>
</html>

schoolstore_project/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>User Registration</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 500px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
        }

        input[type="text"],
        input[type="email"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        button {
            width: 100%;
            padding: 10px;
            background-color: #4caf50;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>User Registration</h1>
        <form action="{% url 'credentials:register' %}" method="post">
            {% csrf_token %}

            <input type="text" name="user_name" placeholder="Enter a User Name" required>
            <input type="password" name="password" placeholder="Password" required>
            <input type="password" name="conpassword" placeholder="Confirm Password" required>
            <button type="submit">Register</button>

          {% for msg in messages %}
          {{msg}}
          {% endfor %}
        </form>
    </div>
</body>
</html>

schoolstore_project/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
    <style>
        button {
    width: 20%;
    padding: 10px;
    background-color: #4caf50;
    color: #fff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease; /* Add a smooth transition effect */
    font-size: 16px;
    font-weight: bold;
    text-transform: uppercase;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Add a subtle box shadow */
}

button:hover {
    background-color: #45a049;
}

button:focus {
    outline: none; /* Remove the default focus outline */
}


        h1 {
            font-size: 50px;
        }

        img {
            max-width: 50%;
            height: auto;
            margin-top: 20px;
        }
    </style>
</head>
<body>
<center><h1>WELCOME</h1>
<img src="../static/img/smile.jpg">
    <br>
    <br>
 <a href="{% url 'storeapp:form' %}"><button type="submit" >Click Here</button></a></center>


</body>
</html>